FROM nginx as nginx

# 时区
ENV TZ=Asia/Shanghai

# 工作目录
WORKDIR /opt/component/

# 复制其他文件
ADD build/ /usr/share/nginx/html/
ADD .github/docker/ ./
COPY .github/docker/ /etc/nginx/

# 权限
#RUN chmod +x /docker-entrypoint.sh
#    sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
RUN apt-get update && \
    apt-get install openssl -y && \
    mkdir -p "/opt/component/web/cert" && \
    openssl dhparam -dsaparam -out /etc/nginx/dhparam.pem 4096


# 运行
ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 80

STOPSIGNAL SIGQUIT

CMD ["nginx", "-g", "daemon off;"]



