# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# uni web 项目一体式构建方案
name: uni-web project build

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ ]
  # 每月 的 一号 凌晨 调度运行
  #  schedule:
  #    - cron: '0 0 */1 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # 拉取main分支最新的项目代码
      - name: git check out main branches
        uses: actions/checkout@v3
        with:
          ref: main

      # ------------------------------------------- node 构建管理模块 ----------------------------------------------------
      - name: npm build
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run build --if-present
      # ------------------------------------------- node 构建管理模块 ----------------------------------------------------

      - name: run shell
        run: ls -al
      - name: run shell
        run: ls -al build

      # -------------------------------------------docker 镜像管理模块----------------------------------------------------
      # 该模块GitHub参考文档是https://github.com/docker/metadata-action#basic
      # 该模块docker官方参考文档是https://docs.docker.com/build/ci/github-actions/examples/#manage-tags-and-labels

      # docker 镜像管理模块 ------> 加载docker镜像元数据管理服务
      - name: docker meta manager service
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: registry.cn-hangzhou.aliyuncs.com/acitrus/uni-web

      # docker 镜像管理模块 ------> 加载docker登陆服务
      - name: docker login service
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: registry.cn-hangzhou.aliyuncs.com

      # docker 镜像管理模块 ------> 加载docker 多平台镜像构建服务
      - name: docker build x service
        uses: docker/setup-buildx-action@v2

      # docker 镜像管理模块 ------> 构建和推送最新的镜像
      - name: docker build and push service
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: .github/docker/DockerFile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # -------------------------------------------docker 镜像管理模块----------------------------------------------------


      - name: rm node_modules
        run: rm -rf node_modules

      # -------------------------------------------服务启动维护管理模块-----------------------------------------------------
      # 该模块GitHub参考文档是https://github.com/appleboy/scp-action
      # 该模块GitHub参考文档是https://github.com/appleboy/ssh-action
      - name: upload ecs server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USER }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          source: "*"
          target: "/opt/component/web"
          rm: true

      - name: restart service
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.ALIYUN_HOST }}
          username: ${{ secrets.ALIYUN_USER }}
          password: ${{ secrets.ALIYUN_PASSWORD }}
          script: |
            cd /opt/component/web/.github/docker
            mkdir -p /opt/component/web/cert
            echo "${{ secrets.NGINX_PEM }}" > /opt/component/web/cert/acitrus.pem
            echo "${{ secrets.NGINX_KEY }}" > /opt/component/web/cert/acitrus.key
            chmod +x ./compose-restart.sh && ./compose-restart.sh

      # -------------------------------------------服务启动维护管理模块-----------------------------------------------------